#' @title uscensuscounty
#' \describe{
  #'   \item{\code{FILEID}} {File Identification}
  #'   \item{\code{STUSAB}}{State/US-Abbreviation (USPS)}
  #'   \item{\code{SUMLEV}}{Summary Level=050 for county}
  #'   \item{\code{GEOVAR}}{Geographic Variant}
  #'   \item{\code{GEOCOMP}}{Geographic Component}
  #'   \item{\code{CHARITER}}{Characteristic Iteration}
  #'   \item{\code{CIFSN}}{Characteristic Iteration File Sequence Number}
  #'   \item{\code{LOGRECNO}}{Logical Record Number}
  #'   \item{\code{GEOID}} {Geographic Record Identifier}
  #'   \item{\code{GEOCODE}}{Geographic Code Identifier}
  #'   \item{\code{REGION}}{Region}
  #'   \item{\code{DIVISION}}{Division}
  #'   \item{\code{STATE}}{State}
  #'   \item{\code{COUNTY}}{County}
  #'   \item{\code{COUNTYCC}}{FIPS County class code}
  #'   \item{\code{COUNTYNS}}{County (NS)}
  #'   \item{\code{COUSUB}}{County Sub Divison (FIPS)}
  #'   \item{\code{COUSUBCC}}{FIPS County Subdivision Class Code}
  #'   \item{\code{COUSUBNS}}{County Subdivision (NS)}
  #'   \item{\code{SUBMCD}}{Subminor Civil Division (FIPS)}
  #'   \item{\code{SUBMCDCC}}{FIPS Subminor Civil Division Class Code}
  #'   \item{\code{SUBMCDNS}}{Subminor Civil Division (NS)}
  #'   \item{\code{ESTATE}}{Estate (FIPS)}
  #'   \item{\code{ESTATECC}}{FIPS Estate Class Code}
  #'   \item{\code{ESTATENS}}{Estate (NS)}
  #'   \item{\code{CONCIT}}{Consolidated City (FIPS)}
  #'   \item{\code{CONCITCC}}{FIPS Consolidated City Class Code}
  #'   \item{\code{CONCITNS}}{Consolidated City (NS)}
  #'   \item{\code{PLACE}}{Place (FIPS)}
  #'   \item{\code{PLACECC}}{FIPS Place Class Code}
  #'   \item{\code{PLACENS}}{Place (NS)}
  #'   \item{\code{TRACT}}{Census Tract}
  #'   \item{\code{BLKGRP}}{Block Group}
  #'   \item{\code{BLOCK}}{Block}
  #'   \item{\code{AIANHH}}{American Indian Area/Alaska Native Area/Hawaiian Home Land (Census)}
  #'   \item{\code{AIHHTLI}}{American Indian Trust Land/Hawaiian Home Land Indicator}
  #'   \item{\code{AIANHHFP}}{American Indian Area/Alaska Native Area/Hawaiian Home Land (FIPS)}
  #'   \item{\code{AIANHHCC}}{FIPS American Indian Area/Alaska Native Area/Hawaiian Home Land Class Code}
  #'   \item{\code{AIANHHNS}}{American Indian Area/Alaska Native Area/Hawaiian Home Land (NS)}
  #'   \item{\code{AITS}}{American Indian Tribal Subdivision (Census)}
  #'   
  #'   \item{\code{AITSFP}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{AITSCC}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{AITSNS}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{TTRACT}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{TBLKGRP}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{ANRC}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{ANRCCC}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{ANRCNS}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{CBSA}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{MEMI}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{CSA}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{METDIV}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{NECTA}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{NMEMI}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{CNECTA}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{NECTADIV}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{CBSAPCI}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{NECTAPCI}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{UA}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{UATYPE}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{UR}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{CD116}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{CD118}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{CD119}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{CD120}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{CD121}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{SLDU18}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{SLDU22}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{SLDU24}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{SLDU26}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{SLDU28}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{SLDL18}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{SLDL22}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{SLDL24}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{SLDL26}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{SLDL28}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{VTD}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{VTDI}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{ZCTA}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{SDELM}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{SDSEC}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{SDUNI}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{PUMA}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{AREALAND}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{AREAWATR}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{BASENAME}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{NAME}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{FUNCSTAT}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{GCUNI}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{POP100}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{HU100}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{INTPTLAT}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{INTPTLON}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{LSADC}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{PARTFLAG}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{UGA}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010001}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010002}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010003}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010004}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010005}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010006}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010007}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010008}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010009}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010010}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010011}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010012}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010013}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010014}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010015}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010016}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010017}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010018}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010019}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010020}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010021}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010022}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010023}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010024}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010025}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010026}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010027}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010028}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010029}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010030}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010031}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010032}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010033}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010034}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010035}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010036}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010037}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010038}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010039}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010040}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010041}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010042}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010043}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010044}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010045}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010046}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010047}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010048}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010049}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010050}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010051}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010052}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010053}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010054}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010055}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010056}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010057}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010058}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010059}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010060}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010061}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010062}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010063}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010064}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010065}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010066}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010067}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010068}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010069}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010070}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0010071}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020001}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020002}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020003}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020004}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020005}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020006}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020007}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020008}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020009}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020010}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020011}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020012}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020013}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020014}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020015}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020016}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020017}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020018}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020019}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020020}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020021}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020022}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020023}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020024}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020025}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020026}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020027}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020028}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020029}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020030}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020031}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020032}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020033}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020034}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020035}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020036}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020037}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020038}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020039}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020040}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020041}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020042}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020043}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020044}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020045}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020046}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020047}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020048}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020049}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020050}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020051}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020052}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020053}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020054}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020055}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020056}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020057}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020058}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020059}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020060}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020061}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020062}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020063}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020064}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020065}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020066}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020067}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020068}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020069}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020070}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020071}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020072}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0020073}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030001}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030002}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030003}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030004}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030005}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030006}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030007}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030008}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030009}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030010}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030011}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030012}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030013}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030014}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030015}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030016}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030017}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030018}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030019}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030020}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030021}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030022}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030023}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030024}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030025}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030026}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030027}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030028}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030029}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030030}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030031}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030032}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030033}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030034}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030035}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030036}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030037}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030038}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030039}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030040}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030041}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030042}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030043}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030044}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030045}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030046}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030047}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030048}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030049}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030050}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030051}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030052}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030053}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030054}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030055}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030056}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030057}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030058}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030059}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030060}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030061}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030062}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030063}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030064}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030065}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030066}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030067}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030068}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030069}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030070}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0030071}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040001}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040002}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040003}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040004}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040005}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040006}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040007}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040008}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040009}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040010}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040011}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040012}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040013}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040014}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040015}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040016}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040017}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040018}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040019}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040020}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040021}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040022}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040023}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040024}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040025}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040026}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040027}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040028}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040029}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040030}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040031}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040032}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040033}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040034}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040035}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040036}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040037}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040038}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040039}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040040}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040041}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040042}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040043}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040044}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040045}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040046}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040047}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040048}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040049}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040050}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040051}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040052}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040053}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040054}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040055}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040056}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040057}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040058}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040059}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040060}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040061}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040062}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040063}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040064}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040065}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040066}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040067}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040068}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040069}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040070}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040071}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040072}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0040073}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{H0010001}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{H0010002}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{H0010003}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0050001}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0050002}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0050003}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0050004}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0050005}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0050006}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0050007}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0050008}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0050009}}{character COLUMN_DESCRIPTION}
  #'   \item{\code{P0050010}}{character COLUMN_DESCRIPTION}
  #'}
  #'@source\url{https://www2.census.gov/programs-surveys/decennial/2020/data/01-Redistricting_File--PL_94-171/}
  "uscensuscounty"